### ISSUE TITLE
ldap3.core.exceptions.LDAPSocketReceiveError: error receiving data: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by tedstrauss** [jupyterhub/ldapauthenticator#100]
Unable to make connection hold to my institutional LDAP server, after trying dozens of combinations of settings. Will be trying to debug with the ldap3 package separately. I have several other web apps that connect to the same LDAP server without trouble, so connecting shouldn't be an issue. 

Here's what I currently have:

```
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = 'ldap://my.jupyterhub.edu'
c.LDAPAuthenticator.use_ssl = True
c.LDAPAuthenticator.server_port = 636
c.LDAPAuthenticator.bind_dn_template = ["CN={username},OU=Faculty,DC=campus,DC=niceschool,DC=edu"]
c.LDAPAuthenticator.escape_userdn = False
c.LDAPAuthenticator.user_search_base = 'OU=Faculty,DC=campus,DC=niceschool,DC=edu'
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = 'loginname'
c.LDAPAuthenticator.lookup_dn_search_password = 'secret'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'sAMAccountName'
```

And here's the trace:

```
[I 2018-08-22 16:06:19.309 JupyterHub app:1581] JupyterHub is now running at https://my.jupyterhub.edu:443/
[D 2018-08-22 16:06:59.141 JupyterHub ldapauthenticator:299] TYPE= 'True'
[D 2018-08-22 16:06:59.143 JupyterHub ldapauthenticator:223] Looking up user with search_base=OU=Faculty,DC=campus,DC=niceschool,DC=edu, search_filter='(sAMAccountName=tstrau)', attributes=sAMAccountName
[E 2018-08-22 16:07:09.147 JupyterHub web:1621] Uncaught exception POST /hub/login?next= (132.206.178.43)
    HTTPServerRequest(protocol='https', host='my.jupyterhub.edu', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='132.206.178.43')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/handlers/login.py", line 83, in post
        user = yield self.login_user(data)
      File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/handlers/base.py", line 328, in login_user
        authenticated = yield self.authenticate(data)
      File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/auth.py", line 227, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/usr/local/lib/python3.4/dist-packages/ldapauthenticator/ldapauthenticator.py", line 301, in authenticate
        resolved_username = self.resolve_username(username)
      File "/usr/local/lib/python3.4/dist-packages/ldapauthenticator/ldapauthenticator.py", line 228, in resolve_username
        is_bound = conn.bind()
      File "/usr/local/lib/python3.4/dist-packages/ldap3/core/connection.py", line 539, in bind
        response = self.post_send_single_response(self.send('bindRequest', request, controls))
      File "/usr/local/lib/python3.4/dist-packages/ldap3/strategy/sync.py", line 124, in post_send_single_response
        responses, result = self.get_response(message_id)
      File "/usr/local/lib/python3.4/dist-packages/ldap3/strategy/base.py", line 331, in get_response
        responses = self._get_response(message_id)
      File "/usr/local/lib/python3.4/dist-packages/ldap3/strategy/sync.py", line 160, in _get_response
        responses = self.receiving()
      File "/usr/local/lib/python3.4/dist-packages/ldap3/strategy/sync.py", line 94, in receiving
        raise communication_exception_factory(LDAPSocketReceiveError, exc)(self.connection.last_error)
    ldap3.core.exceptions.LDAPSocketReceiveError: error receiving data: [Errno 104] Connection reset by peer
    
[D 2018-08-22 16:07:09.162 JupyterHub base:633] No template for 500
[E 2018-08-22 16:07:09.231 JupyterHub log:114] {
      "Cache-Control": "max-age=0",
      "Origin": "https://my.jupyterhub.edu",
      "Referer": "https://my.jupyterhub.edu/hub/login?next=",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.9,fr;q=0.8",
      "X-Forwarded-For": "132.206.178.43",
      "Connection": "close",
      "Accept-Encoding": "gzip, deflate, br",
      "Host": "my.jupyterhub.edu",
      "Content-Length": "39",
      "Cookie": "_ga=GA1.2.966485689.1530210970; SSESS4d9119e6b043279d0132568957bd2381=Vbadb0KpItO9NrkKkD5tBMkuA9qKkGI2Ni_UeZjAUUQ; _gid=GA1.2.264270059.1534783765",
      "X-Forwarded-Host": "my.jupyterhub.edu",
      "X-Forwarded-Port": "443",
      "X-Forwarded-Proto": "https"
```

**Comment by tedstrauss** [comment]
This bug appears to be fixed after changing:

`c.LDAPAuthenticator.server_address = 'ldap://my.jupyterhub.edu'`

to

`c.LDAPAuthenticator.server_address = 'ldaps://my.jupyterhub.edu'`

I'm still unable to authenticate. Next bug report here:

https://github.com/jupyterhub/ldapauthenticator/issues/101

**Comment by sigurdurb** [comment]
I had the same error msg with 'ldap://' and then switched to 'ldaps://' also but now I just get
` [W 2018-08-23 23:03:22.468 JupyterHub ldapauthenticator:230] Can't connect to LDAP`

Did you have to do any server configurations with certificates or such when using ssl and ldaps ?
So I also have 
c.LDAPAuthenticator.use_ssl = True
c.LDAPAuthenticator.server_port = 636

I can also telnet the ldap server and it says connected for port 636 but not 389, [As is recommended when testing ldap here:](https://www.dirwiz.com/kb/454) and the sysadmin at my school tells me to use ssl so I guess 636 should work.

**Comment by tedstrauss** [comment]
Here is the command I use to start JupyterHub:

```
sudo jupyterhub --debug --ip my.jupyter.hub --port 443  --ssl-cert /path/to/ssl.crt --ssl-key /oath/to/ssl.key
```

And settings in `jupyterhub_config.py`:

```
c.JupyterHub.ssl_cert = '/path/to/ssl.crt'
c.JupyterHub.ssl_key = '/path/to/ssl.key'
```
