### ISSUE TITLE
KeyError: 'getpwnam(): name not found: myname'

### ISSUE THREAD

**Issue by ericweinberg** [jupyterhub/ldapauthenticator#107]
I'm not sure if this a jupyterhub or a ldapauthenticator issue.  

I think I'm getting through the ldap configuration, but when i start a new notebook i get a 500 error. 

I'm probably just missing a step, but not sure what it is. 

```
[I 2018-10-30 19:18:28.164 JupyterHub log:122] 200 GET /hub/login (@::ffff:10.2.1.1) 5.84ms
[D 2018-10-30 19:18:33.089 JupyterHub ldapauthenticator:299] TYPE= 'False'
[D 2018-10-30 19:18:33.090 JupyterHub ldapauthenticator:223] Looking up user with search_base=OU=Users,DC=mycompany,DC=com, search_filter='(sAMAccountName=myuser)', attributes=sAMAccountName
[D 2018-10-30 19:18:33.156 JupyterHub ldapauthenticator:278] Attempting to bind myname with CN=myname,OU=Users,DC=mycompany,DC=com
[D 2018-10-30 19:18:33.274 JupyterHub ldapauthenticator:333] Status of user bind myname with CN=myname,OU=Users,DC=mycompany,DC=com : True
[D 2018-10-30 19:18:33.278 JupyterHub base:268] Setting cookie for myname: jupyter-hub-token, {'httponly': True, 'secure': True}
[I 2018-10-30 19:18:33.279 JupyterHub base:346] User logged in: myname
[D 2018-10-30 19:18:33.279 JupyterHub base:421] Initiating spawn for myname
[E 2018-10-30 19:18:33.317 JupyterHub user:427] Unhandled error starting myname's server: 'getpwnam(): name not found: myname'
[D 2018-10-30 19:18:33.383 JupyterHub base:427] 0/100 concurrent spawns
[D 2018-10-30 19:18:33.383 JupyterHub base:430] 0 active servers
[E 2018-10-30 19:18:33.383 JupyterHub web:1591] Uncaught exception POST /hub/login?next= (::ffff:10.2.1.1)
    HTTPServerRequest(protocol='https', SNIP)
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/login.py", line 94, in post
        yield self.spawn_single_user(user)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 475, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/conda/lib/python3.6/types.py", line 248, in wrapped
        coro = func(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/spawner.py", line 968, in start
        env = self.get_env()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/spawner.py", line 960, in get_env
        env = self.user_env(env)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/spawner.py", line 947, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found: myuser'
```

**Comment by ericweinberg** [comment]
Actually, i just manually added the user to the linux machine running jupyterhub and things appear to be working now.  Am I missing a configuration piece somewhere, otherwise why have LDAP if i still have to create users.

**Comment by dimitar-petrov** [comment]
I am facing the same issue here.
Did you manage find the root cause.

**Comment by ericweinberg** [comment]
I don't know what the root cause is. Adding the user to the local file system should resolve the error. It seems to me that should be tied into authenticating with LDAP somehow.

**Comment by raiden2012** [comment]
How about checking this out: https://github.com/jupyterhub/ldapauthenticator/issues/19

**Comment by babaMar** [comment]
Adding
```
from subprocess import check_call


def pre_spawn_hook(spawner):
    username = spawner.user.name
    try:
        check_call(['useradd', '-ms', '/bin/bash', username])
    except Exception as e:
        print(f'{e}')
c.Spawner.pre_spawn_hook = pre_spawn_hook
```
helped for me

**Comment by JorgeRuizITCL** [comment]
I had the exact same issue with the BatchSpawner module. 

The easiest way to solve this was to install LDAP in the Docker Container as it was already configured in the host and uninstall this plug-in.

Dockerfile:
```Dockerfile
RUN apt install -y libnss-ldap libpam-ldap ldap-utils
```

Compose:
```yaml
volumes:
      - /etc/nsswitch.conf:/etc/nsswitch.conf:ro
      - /etc/pam.d/common-session:/etc/pam.d/common-session:ro
      - /etc/pam.d/common-password:/etc/pam.d/common-password:ro
      - /etc/ldap.conf:/etc/ldap.conf:ro
```

**Comment by consideRatio** [comment]
I've opened #261 to capture that this is a discussion about making the authenticator able to create users on the fly, and not being able to do so by default leads to this error.
