### ISSUE TITLE
Failed to establish secure ldap connection on CentOS 7 running in a docker container

### ISSUE THREAD

**Issue by saba-ja** [jupyterhub/ldapauthenticator#140]
**Description of issue**: 
When trying to use secure ldap connection (ldaps://ldap.example.com) on CentOS 7 running in a docker container the following exception occurs: 
LDAPSocketOpenError (unable to open socket)

----------
This is the entire error trace:

```
Uncaught exception POST /hub/login?next= (my_ip)
    HTTPServerRequest(protocol='https', host='my_host', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='my_ip')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/jupyterhub/handlers/login.py", line 144, in post
        user = await self.login_user(data)
      File "/opt/conda/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 687, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/conda/lib/python3.7/site-packages/jupyterhub/auth.py", line 383, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/conda/lib/python3.7/site-packages/ldapauthenticator/ldapauthenticator.py", line 306, in authenticate
        resolved_username = self.resolve_username(username)
      File "/opt/conda/lib/python3.7/site-packages/ldapauthenticator/ldapauthenticator.py", line 228, in resolve_username
        is_bound = conn.bind()
      File "/opt/conda/lib/python3.7/site-packages/ldap3/core/connection.py", line 530, in bind
        self.open(read_server_info=False)
      File "/opt/conda/lib/python3.7/site-packages/ldap3/strategy/sync.py", line 56, in open
        BaseStrategy.open(self, reset_usage, read_server_info)
      File "/opt/conda/lib/python3.7/site-packages/ldap3/strategy/base.py", line 147, in open
        raise LDAPSocketOpenError('unable to open socket', exception_history)
    ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', **[(LDAPSocketOpenError('socket ssl wrapping error: [Errno 0] Error'), ('', ))])**
```

----------

After a week of digging and struggle I narrowed down the issue to the following:

**Root of the Issue**: 
Tls object with is needed to establish the SSL connection on LDAP3, but jupyterhub-ldapauthenticator library does not provide this option in file ldapauthenticator/ldapauthenticator.py

----------
Explanation:
Per following link to establish SSL "you should properly configure the Server object addind a Tls object with the relevant ssl configuration":
https://ldap3.readthedocs.io/ssltls.html#the-tls-object

I used the following script to verify the ldap3 connection:

```python
import ldap3
import ssl 

server_address = 'ldaps://ldap.example.com'
user_search_base = 'ou=people,dc=dir,dc=example,dc=com'
lookup_dn_user_dn_attribute = 'uid'
username = 'my_username'
certificate_key_file_addr = 'certificate.key'
certificate_crt_file_addr = 'certificate.crt'

tls = ldap3.Tls(local_private_key_file=certificate_crt_file_addr, local_certificate_file=certificate_crt_file_crt, validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1)
server = ldap3.Server(host=server_address, port=636, use_ssl=True, tls=tls)
conn = ldap3.Connection(server, auto_bind=True, version=3)

conn.start_tls()
is_bound = conn.bind()
assert is_bound
conn.search(
    search_base=user_search_base,
    search_scope=ldap3.SUBTREE,
    search_filter=f'(uid={username})',
    attributes=ldap3.ALL_ATTRIBUTES
)
print(conn.response[0])
resp = conn.response[0]
print(resp['attributes'][lookup_dn_user_dn_attribute])
```
With the above script I was able to establish the secure ldap connection.
If you remove the TLS object the connection will fail.

----------
**Workaround**:

To resolve the issue I added the following to the l **/opt/conda/lib/python3.7/site-packages/ldapauthenticator/ldapauthenticator.py** to the following function:

https://github.com/jupyterhub/ldapauthenticator/blob/f8701d47463048adde9f31ed8c3d8ba8233eb9b5/ldapauthenticator/ldapauthenticator.py#L278

```python
import ssl
...
def get_connection(self, userdn, password):
    
    tls = ldap3.Tls(local_private_key_file='/etc/ssl/certificate.key',
                    local_certificate_file='/etc/ssl/certificate.crt',
                    validate=ssl.CERT_REQUIRED,
                    version=ssl.PROTOCOL_TLSv1)
    
    server = ldap3.Server(self.server_address,
                          port=self.server_port,
                          use_ssl=self.use_ssl,
                          tls=tls)   
```
AND the issue was resolved!
---------
**Feature request**:
Now the feature request is to add option to set the TLS options from the jupyterhub_config.py so user can directly add the certificates in the config file instead of directly changing the source code.

**Comment by consideRatio** [comment]
Thank you for a great investigation and writeup @saba-ja!! I'm sorry for the super late reply. Its become clear from this issue and others that we really need to get #49 resolved.

Going for a close on this, where the feature request is tracked via #49 for the moment.
