### ISSUE TITLE
500 Error if "Sign In" Button Clicked Multiple Times

### ISSUE THREAD

**Issue by danroliver** [jupyterhub/ldapauthenticator#51]
If a user clicks the "Sign In" button multiple times, or attempts to authenticate simultaneously in different tabs, an error is raised and the user gets forwarded to a 500 page.
From the logs:
```
[D 2017-09-20 15:30:24.295 JupyterHub ldapauthenticator:267] Attempting to bind username with cn=username,OU=Users,DC=wikimedia,DC=org
[I 2017-09-20 15:30:24.590 JupyterHub spawner:766] PVC claim-username already exists, so did not create new pvc.
[D 2017-09-20 15:30:25.826 JupyterHub ldapauthenticator:283] TYPE= 'False'
[D 2017-09-20 15:30:25.826 JupyterHub ldapauthenticator:267] Attempting to bind username with cn=username,OU=Users,DC=wikimedia,DC=org
[E 2017-09-20 15:30:26.141 JupyterHub web:1590] Uncaught exception POST /hub/login?next= (192.168.166.128)
    HTTPServerRequest(protocol='http', host='jupyter.wikimedia.org', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='192.168.166.128', headers={'Host': 'jupyter.wikimedia.org', 'Origin': 'https://jupyter.wikimedia.org', 'Cache-Control': 'max-age=0', 'X-Forwarded-Host': 'jupyter.wikimedia.org', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36', 'Accept-Language': 'en-US,en;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '80', 'X-Forwarded-For': '192.168.166.128', 'Content-Length': '42', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'close', 'Referer': 'https://jupyter.wikimedia.org/hub/login?next='})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 306, in spawn_single_user
        raise RuntimeError("Spawn already pending for: %s" % user.name)
    RuntimeError: Spawn already pending for: username
    
[D 2017-09-20 15:30:26.141 JupyterHub base:462] No template for 500
[E 2017-09-20 15:30:26.145 JupyterHub log:99] {
      "Host": "jupyter.wikimedia.org",
      "Origin": "https://jupyter.wikimedia.org",
      "Cache-Control": "max-age=0",
      "X-Forwarded-Host": "jupyter.wikimedia.org",
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
      "Accept-Language": "en-US,en;q=0.8",
      "Upgrade-Insecure-Requests": "1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "80",
      "X-Forwarded-For": "192.168.166.128",
      "Content-Length": "42",
      "Accept-Encoding": "gzip, deflate, br",
      "Connection": "close",
      "Referer": "https://jupyter.wikimedia.org/hub/login?next="
    }
[E 2017-09-20 15:30:26.145 JupyterHub log:100] 500 POST /hub/login?next= (@192.168.166.128) 317.60ms
```

**Comment by minrk** [comment]
Are you using JupyterHub 0.7? I believe this is fixed in 0.8 (release candidate earlier this week).

**Comment by danroliver** [comment]
Yes, this is with 0.7.
