### ISSUE TITLE
pyasn1 Error

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/ldapauthenticator#52]
After updating to master I'm now seeing the below error when logging in when it used to work previously. We're using Active Directory. Likely a config issue but I thought I'd post so as to not lose the traceback. Even if it does end up being a config issue it should probably not throw an unhandled exception?
```
[E 2017-09-28 10:23:46.736 JupyterHub web:1590] Uncaught exception POST /hub/login?next= (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::1', headers={'X-Forwarded-Host': 'localhost:8000', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '8000', 'X-Forwarded-For': '::1', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Referer': 'http://localhost:8000/hub/login', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded', 'Upgrade-Insecure-Requests': '1', 'Origin': 'http://localhost:8000', 'Cache-Control': 'max-age=0', 'Content-Length': '39', 'Connection': 'close', 'Host': 'localhost:8000'})
    Traceback (most recent call last):
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\web.py", line 1511, in _execute
        result = yield result
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "c:\dev\src\jupyterhub\jupyterhub\handlers\login.py", line 82, in post
        user = yield self.login_user(data)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "c:\dev\src\jupyterhub\jupyterhub\handlers\base.py", line 327, in login_user
        authenticated = yield self.authenticate(data)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "c:\dev\src\jupyterhub\jupyterhub\auth.py", line 221, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 292, in wrapper
        result = func(*args, **kwargs)
      File "C:\Miniconda3\envs\jupyterhub\lib\types.py", line 248, in wrapped
        coro = func(*args, **kwargs)
      File "c:\dev\src\ldapauthenticator\ldapauthenticator\ldapauthenticator.py", line 320, in authenticate
        conn = getConnection(userdn, username, password)
      File "c:\dev\src\ldapauthenticator\ldapauthenticator\ldapauthenticator.py", line 284, in getConnection
        auto_bind=ldap3.AUTO_BIND_TLS_BEFORE_BIND,
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\ldap3\core\connection.py", line 288, in __init__
        self.start_tls(read_server_info=False)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\ldap3\core\connection.py", line 969, in start_tls
        if self.server.tls.start_tls(self) and self.strategy.sync:  # for async connections _start_tls is run by the strategy
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\ldap3\core\tls.py", line 209, in start_tls
        result = connection.extended('1.3.6.1.4.1.1466.20037')
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\ldap3\core\connection.py", line 935, in extended
        response = self.post_send_single_response(self.send('extendedReq', request, controls))
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\ldap3\strategy\base.py", line 274, in send
        self.connection.request = BaseStrategy.decode_request(ldap_message)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\ldap3\strategy\base.py", line 559, in decode_request
        result = extended_request_to_dict(component)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\ldap3\operation\extended.py", line 55, in extended_request_to_dict
        return {'name': str(request['requestName']), 'value': str(request['requestValue']) if request['requestValue'] else None}
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\pyasn1\type\base.py", line 249, in __bool__
        return self._value and True or False
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\pyasn1\type\base.py", line 164, in plug
        raise error.PyAsn1Error('Uninitialized ASN.1 value ("%s" attribute looked up)' % name)
    pyasn1.error.PyAsn1Error: Uninitialized ASN.1 value ("__bool__" attribute looked up)
```

**Comment by dhirschfeld** [comment]
I'm going to close this as it turns out the latest `ldap3` for py36 using conda is version `1.0.4` . Installing the latest `2.3` via pip seems to have solved this particular problem.
