### ISSUE TITLE
500 Error with escape_userdn=True

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/ldapauthenticator#53]
The below error seems to occur when my username has no special characters:
```
[E 2017-09-28 10:42:09.532 JupyterHub web:1590] Uncaught exception POST /hub/login?next= (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::1', headers={'X-Forwarded-Host': 'localhost:8000', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '8000', 'X-Forwarded-For': '::1', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Referer': 'http://localhost:8000/hub/login?next=', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded', 'Upgrade-Insecure-Requests': '1', 'Origin': 'http://localhost:8000', 'Cache-Control': 'max-age=0', 'Content-Length': '39', 'Connection': 'close', 'Host': 'localhost:8000'})
    Traceback (most recent call last):
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\web.py", line 1511, in _execute
        result = yield result
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "c:\dev\src\jupyterhub\jupyterhub\handlers\login.py", line 82, in post
        user = yield self.login_user(data)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "c:\dev\src\jupyterhub\jupyterhub\handlers\base.py", line 327, in login_user
        authenticated = yield self.authenticate(data)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "c:\dev\src\jupyterhub\jupyterhub\auth.py", line 221, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 292, in wrapper
        result = func(*args, **kwargs)
      File "C:\Miniconda3\envs\jupyterhub\lib\types.py", line 248, in wrapped
        coro = func(*args, **kwargs)
      File "c:\dev\src\ldapauthenticator\ldapauthenticator\ldapauthenticator.py", line 301, in authenticate
        resolved_username = self.resolve_username(username)
      File "c:\dev\src\ldapauthenticator\ldapauthenticator\ldapauthenticator.py", line 227, in resolve_username
        conn = ldap3.Connection(server, user=self.escape_userdn_if_needed(self.lookup_dn_search_user), password=self.lookup_dn_search_password)
      File "c:\dev\src\ldapauthenticator\ldapauthenticator\ldapauthenticator.py", line 250, in escape_userdn_if_needed
        return escape_filter_chars(userdn)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\ldap3\utils\conv.py", line 36, in escape_filter_chars
        output = text.replace('\\', r'\5c')
    AttributeError: 'NoneType' object has no attribute 'replace'
```
...if I try to use `DOMAIN\USERNAME` I Instead see a warning:
```
[W 2017-09-28 10:46:29.836 JupyterHub ldapauthenticator:290] username:DOMAIN\USERNAME Illegal characters in username, must match regex ^[a-z][.a-z0-9_-]*$
```

**Comment by dhirschfeld** [comment]
I'm going to close this as it turns out the latest `ldap3` for py36 using conda is version `1.0.4` . Installing the latest `2.3` via pip seems to have solved this particular problem.
