### ISSUE TITLE
Need help in configuring AD accounts

### ISSUE THREAD

**Issue by PushpalathaT** [jupyterhub/ldapauthenticator#60]
Hello, 

I am trying to configure Active Directory in Jupyterhub using ldapauthenticator (latest version pulled from github), below is my configuration for LDAP/AD, 

```
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = 'abc.xyz.com'
c.LDAPAuthenticator.bind_dn_template = 'cn={username},DC=xyz,DC=com'
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.use_ssl = False
c.LDAPAuthenticator.server_port = 3268

c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = 'serviceaccount@abc.xyz.COM'
c.LDAPAuthenticator.lookup_dn_search_password = 'password'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'cn'

c.LDAPAuthenticator.user_search_base = 'DC=xyz,DC=com'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.allowed_groups = []
```

But, getting below error in the logs, 
```
[D 2018-01-16 10:08:36.664 JupyterHub ldapauthenticator:299] TYPE= 'False'
[D 2018-01-16 10:08:36.665 JupyterHub ldapauthenticator:223] Looking up user with search_base=DC=xyz,DC=com, search_filter='(sAMAccountName=username)', attributes=sAMAccountName
[D 2018-01-16 10:08:38.719 JupyterHub ldapauthenticator:278] Attempting to bind username with c
[D 2018-01-16 10:08:39.159 JupyterHub ldapauthenticator:328] Status of user bind username with c : False
    LDAPBindError: automatic bind not successful - invalidCredentials
[D 2018-01-16 10:08:39.160 JupyterHub ldapauthenticator:278] Attempting to bind username with n
[D 2018-01-16 10:08:39.603 JupyterHub ldapauthenticator:328] Status of user bind username with n : False
    LDAPBindError: automatic bind not successful - invalidCredentials
[D 2018-01-16 10:08:39.604 JupyterHub ldapauthenticator:278] Attempting to bind username with =
[D 2018-01-16 10:08:40.039 JupyterHub ldapauthenticator:328] Status of user bind username with = : False
    LDAPBindError: automatic bind not successful - invalidCredentials_**
[E 2018-01-16 10:08:40.040 JupyterHub web:1591] Uncaught exception POST /hub/login?next= (<<IPAddress>>)
    HTTPServerRequest(protocol='http', host='<<IPAddress>>:8001', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='<<IPAddress>>', headers={'Content-Length': '35', 'X-Forwarded-Port': '8001', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36', 'Connection': 'close', 'Host': '<<IPAddress>>:8001', 'Upgrade-Insecure-Requests': '1', 'Content-Type': 'application/x-www-form-urlencoded', 'Referer': 'http://<<IPAddress>>:8001/hub/login?next=', 'X-Forwarded-For': '<<IPAddress>>', 'X-Forwarded-Host': '<<IPAddress>>:8001', 'Origin': 'http://<<IPAddress>>:8001', 'Accept-Language': 'en-US,en;q=0.9', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-Proto': 'http', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/apps/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/apps/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 83, in post
        user = yield self.login_user(data)
      File "/apps/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 328, in login_user
        authenticated = yield self.authenticate(data)
      File "/apps/anaconda3/lib/python3.5/site-packages/jupyterhub/auth.py", line 227, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/apps/anaconda3/lib/python3.5/types.py", line 243, in wrapped
        coro = func(*args, **kwargs)
      File "/tmp/ldapauthenticator/ldapauthenticator/ldapauthenticator.py", line 311, in authenticate
        userdn = dn.format(username=resolved_username)
    ValueError: Single '{' encountered in format string

[D 2018-01-16 10:08:40.049 JupyterHub base:633] No template for 500
[E 2018-01-16 10:08:40.109 JupyterHub log:114] {
      "Content-Length": "35",
      "X-Forwarded-Port": "8001",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36",
      "Connection": "close",
      "Host": "<<IPAddress>>:8001",
      "Upgrade-Insecure-Requests": "1",
      "Content-Type": "application/x-www-form-urlencoded",
      "Referer": "http://<<IPAddress>>:8001/hub/login?next=",
      "X-Forwarded-For": "<<IPAddress>>",
      "X-Forwarded-Host": "<<IPAddress>>:8001",
      "Origin": "http://<<IPAddress>>:8001",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Accept-Encoding": "gzip, deflate",
      "X-Forwarded-Proto": "http",
      "Cache-Control": "max-age=0"
    }
[E 2018-01-16 10:08:40.110 JupyterHub log:122] 500 POST /hub/login?next= (@<<IPAddress>>) 3447.59ms
```

Any help to resolve this issue will be highly appreciated. 

Thanks

**Comment by cr42** [comment]
The bind template needs to be a list.

Change the following:
`c.LDAPAuthenticator.bind_dn_template = 'cn={username},DC=xyz,DC=com'`

To this:
`c.LDAPAuthenticator.bind_dn_template = ['cn={username},DC=xyz,DC=com']`

**Comment by parmeshwor** [comment]
May be this is not related but, though i changed the config with,
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
Jupyterhub is still doing PAM authentication . Am i missing something ?

**Comment by dhirschfeld** [comment]
Thanks for chiming in @cr42 - that looks like an accurate analysis of the problem so I'll go ahead and close this.

Note: In the soon-to-be-released version this shouldn't be a problem:
https://github.com/jupyterhub/ldapauthenticator/blob/cb47d0fb1ee8f39798da9f13181f172d2f824b75/ldapauthenticator/ldapauthenticator.py#L308-L310
