### ISSUE TITLE
Allow configuring groupattributes in group search

### ISSUE THREAD

**Issue by paul-english** [jupyterhub/ldapauthenticator#62]
I'm not the best understanding LDAP standards or syntax but it seems that currently the authenticator is limited in the group attributes it understands: https://github.com/jupyterhub/ldapauthenticator/blob/7545ba0fe43ca8a01bd66b8a3bb6fc6b8114b34a/ldapauthenticator/ldapauthenticator.py#L343

The LDAP server I'm working with uses `memberOf` so we have to skip using allowed groups at the moment.

This might be another worthwhile config option for this authenticator.

**Comment by kinow** [comment]
+1, had the same issue. I'm using a Docker image, which gives you something similar to OpenLDAP tree and schema, with `member` in the schema for groups.

As the search is hard-coded to use these three attributes, the LDAP library raises an exception due to an invalid attribute in the group search.

```
[E 2020-07-09T12:34:49.272 JupyterHub web:1788] Uncaught exception POST /hub/login?next= (::ffff:127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:127.0.0.1')
    Traceback (most recent call last):
      File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/jupyterhub/handlers/login.py", line 144, in post
        user = await self.login_user(data)
      File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/jupyterhub/handlers/base.py", line 699, in login_user
        authenticated = await self.authenticate(data)
      File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/jupyterhub/auth.py", line 383, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/ldapauthenticator/ldapauthenticator.py", line 443, in authenticate
        search_scope=ldap3.BASE,
      File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/ldap3/core/connection.py", line 802, in search
        raise LDAPAttributeError('invalid attribute type ' + attribute_name_to_check)
    ldap3.core.exceptions.LDAPAttributeError: invalid attribute type memberUid

```

I think we could just make it an option in the authenticator, using the current values as default for backward compatibility, but allowing users to specify the group filter, and the group attributes. I edited those values manually in my virtual environment and the group search worked flawlessly after that :+1:
